### ISSUE TITLE
Name must start with "dapp-peg"

### ISSUE THREAD

**Issue by katelynsills** [Agoric/dapp-pegasus#19]
As reported on Discord, when trying agoric init --dapp-template dapp-pegasus <project-name>
one gets an error:
```  
Error#1: <project-name>/ui/package.json: "name" must start with "dapp-peg"
     at initMain (/Users/benny/projects/agoric/agoric-sdk/packages/agoric-cli/lib/init.js:56:13)
    at async Promise.all (index 0)
    at async main (/Users/benny/projects/agoric/agoric-sdk/packages/agoric-cli/lib/main.js:202:5)
```

**Comment by michaelfig** [comment]
Resolved and tested on current `main`.
