### ISSUE TITLE
Unable to Deploy API Handler

### ISSUE THREAD

**Issue by Alfie** [Agoric/dapp-pegasus#56]
When I run the the agoric deploy command the contract deploys successfully, however the API fails to load because it is being processed as CommonJS

```
alfie@alfies-MacBook-Pro pegasus % agoric deploy ./contract/deploy.js ./api/deploy.js
Open CapTP connection to ws://127.0.0.1:8000/private/captp...o
agoric: deploy: running /Users/alfie/Documents/runToTerra/research/pegasus/contract/deploy.js
agoric: deploy: Deploy script will run with standardthings/esm emulation
- SUCCESS! contract code installed on Zoe
-- Contract Name: pegasus
-- InstallationHandle Register Key: 1530981318
writing /Users/alfie/Documents/runToTerra/research/pegasus/conf/installationConstants.js
agoric: deploy: running /Users/alfie/Documents/runToTerra/research/pegasus/api/deploy.js
agoric: deploy: Deploy script will run with standardthings/esm emulation
- SUCCESS! contract instance is running on Zoe
-- Contract Name: pegasus
-- Instance Registry Key: 984638224
-- Peg Registry Key
agoric: (TypeError#1)
TypeError#1: Failed to load module "./gaiaTransfer.js" in package "file:///Users/alfie/Documents/runToTerra/research/pegasus/api/src/" (1 underlying failures: Unexpected import statement in CJS module.
  at file:///Users/alfie/Documents/runToTerra/research/pegasus/api/src/gaiaTransfer.js:1:8

  at async bundleZipBase64 (packages/bundle-source/src/index.js:136:17)
  at async deployApi (/Users/alfie/Documents/runToTerra/research/pegasus/api/deploy.js:99:18)
  at async WebSocket.<anonymous> (packages/agoric-cli/src/deploy.js:264:13)
```

I tried changing gaiaTransfer.js to a .mjs file as a quickfix but then nodejs is unable to find the agoric modules

```
agoric: deploy: Deploy script will run with standardthings/esm emulation
- SUCCESS! contract instance is running on Zoe
-- Contract Name: pegasus
-- Instance Registry Key: 715805464
-- Peg Registry Key
agoric: (TypeError#1)
TypeError#1: Failed to load module "./src/gaiaTransfer.mjs" in package "file:///Users/alfie/Documents/runToTerra/research/pegasus/api/" (1 underlying failures: Cannot find external module "@agoric/pegasus" in package file:///Users/alfie/Documents/runToTerra/research/pegasus/api/

  at async bundleZipBase64 (packages/bundle-source/src/index.js:136:17)
  at async deployApi (/Users/alfie/Documents/runToTerra/research/pegasus/api/deploy.js:99:18)
  at async WebSocket.<anonymous> (packages/agoric-cli/src/deploy.js:264:13)

```
Is this a node problem? I am running v14.15.1, I tried version 16 but was unable to build the agoric sdk using that version. I know this code may not currently be maintained, so I am open to other methods of testing pegasus on my machine, any method to get a connection from agoric to the broader IBC ecosystem would be appreciated. Thanks!

**Comment by Alfie** [comment]
I found the pegasus demo in the monorepo. Sorry, should have done more digging before opening the issue.
